{% set version = '2.2-5.6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sm
  version: {{ version|replace("-", "_") }}

source:
  fn: sm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/sm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/sm/sm_{{ version }}.tar.gz
  sha256: b890cd7ebe8ed711ab4a3792c204c4ecbe9e6ca1fd5bbc3925eba5833a839c30

# This requires full tcltk support in R, which doesn't work in Windows at the moment
build:
  merge_build_host: True  # [win]
  skip: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rgl, misc3d, akima, gam, tkrplot, rpanel (>= 1.1-4), tcltk
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('sm')"           # [not win]
    - "\"%R%\" -e \"library('sm')\""  # [win]

about:
  home: http://www.stats.gla.ac.uk/~adrian/sm
  license: GPL (>= 2)
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'
  summary: This is software linked to the book 'Applied Smoothing Techniques for Data Analysis
    - The Kernel Approach with S-Plus Illustrations' Oxford University Press.
  license_family: GPL3

extra:
   recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
