travis:
  secure:
    BINSTAR_TOKEN: F+sye9pXmVV2uK12WZ1qqiU9DjHHBdaFaq9lrOBnXQtL06elsz9L4Nr2N7Y1fkAt9z00IhSQassGXckyyCynVk+EE16mLEVomDIwD7nA46Zo0/RiaPzLeGec1Qvr+BZcaZqWrXfGcKoALFroRh8J6xxndICT+3Frzd7Ts8NLganTqANSmPVdzRKo4mhcO4Ikjh8QwvHgUzshmhqfoZuLxjp0B2s8DKs3P21IeoA8YYhE1/djJ49nHwGi8RYU64+VHethuHR3qaFgLj/1hqH+/wZR+0vNgxepqpO0Hwat/U17HBRDEOkVlUTkIsQdMdTO/bMx5AA08lI4u3wItfc5v3pURkJodAWrwxY+fhR1C13hM9iyYrYhj6LvnPO3FzXEPd0iwUyVt2pO2lM9Rup/f3nj7pKHh6V4sgnN9Fn1GPMdrswl8F54N7P9bcvwrz/T40+Kh4iLSiBbeYKxQjWDtkVwwJelEkwfVnCZpAfKKYJdXfaVystZ5UxnNIN4/nzgl7mjhzeFyVSNaVvu3lZAnTrqCB1rdrZP/XAAZZvkNmH+WbAFrratviqXUSj/qnwDjM/3vI+NyBBNPnFmRSBrouZc7X+5BEp+j24CaP8puoelPhRcmZJaY48ZP5lfJd+0TOeMQEYeTOPKW2+2A4XChQNrRnqJ/N//uv59CeA9q5k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
