travis:
  secure:
    BINSTAR_TOKEN: cHWSqT51QkkyZyNdgwLAxeXtbhWNx89zkbBpL2Yl3x9XA8aWucGRZiXwTRukpdU0vZUC8Lrp4F7e1UBaki6uGpT/V6PPMKPTHQCZbCAvoWcSqXSjbHjOVH13BpO4ZN0oENi5b7GBxNkUP7M0ava8B8SeHRFukkBuyCwVaPEonZQ6/EBLB2zNkc4EdZg/YIvhdRtICkC6aS/N0jk08NHXZ+HP6BpDVuDfE7clXAszZN0ZJtqJ8INTszSnvPh4RXL9CxFx2WNK6C5RNUGGzZXkLwW0opmnP3OnAKzl+toP2aJ8QJe1mMPZOtqU98Xf7shangOI4A6rH4tMQUpVAcBLY+Zobq5CeN1wE4O+cSjctZ+aEwRTkiMKMvTMc4ZSYmCtugrUq9COpCcHL97LMvKqQ0SBhyWfR5IDCGjsVDbvbxAc70EJ4eA2RtOBUlikXRwawUUxlpviiqVcZ/UYI1Vafp9z5eQvUvOFJomihRkbe8/OuQ2p+zZG4HHKn/2/BOv5L554dhGDjSr6nYJMBl6prSFEW9Dz82WsilGcEvsSb2AC+kEJnPk4W3NInRzUrwEEnZbcRAijrF+dspByU04HtNy8FNTfEFqZ/SF/2vreDbYtO4LoZIkvvTiy5duaQAcPzfHnmo5WdMViQ81y7Rf/RNywEBaKRZvjrc+5FOjABz8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
