travis:
  secure:
    BINSTAR_TOKEN: IAD00n1pLeEd1iWLBShbCMgWOQfxRmWZQyI7pL/9d2kFyIulV6fVAfRfVMVMLnmzoda9tD1kQEEPobsFEkFB1qCdOqSpKmlQ+zx/BT6E16RWLMajb3kIPmeUcJN8NxGft9pieWql/ATjO+Q93GW9AECvOMPBXtHQkJZ0PZDQv4Gzpd9Vsm6JdMaWzj6SNp3cG4OgHFmGTszg58iWqH4TDtMebgpdNVAN5Bqeyu0YeuMM+m+ntfJQb0YGAAcpKc0NdwrbYE6wYQG1hZGaAOqyXRma+ez7TKeF0wGUD/qDPjhdDBZJVRBdx0s19t3d7cp3lrs5F9rVz0GNyaNAcZr+AqBpJYJL1KByGq8l6Xztqqg4L/B2jrQsK/ZrwaPBqS6jXepisTeNoTQfXNnNjOYFoJqsPU9Uc8OWiEz4tEqHhYMeQ1Jsf5HlSR+5OMUS1iFFghcRXmz67+Lb5OhgETFeJiI4w5fDr0CTy0WB0spYOHd9C1SgwGtIFoBfxMULlDDF6Y/mhV0/MMshRfUURqFfMP79OsLTPcfRYqMQ+5t24ueg3SROGC67d8arqu2CF3AMpPqBfBtKuqOR510xOjggCO6BCUSSmi9yTqW/4oEqXfioUK1zHW6UcFTg8gx0dA9Vyz6PlfTaDv4O0CxMMHtoMGqL5lHXOjB2YLxcAolxaD0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
