travis:
  secure:
    BINSTAR_TOKEN: QNtu9zgPITOvx5YOV7mD0GUWMl00oN7xXIzC+Wjt2XL5I6gKFwWT1xgRwDQ8tJBhRMW3E6XTfF25Ctt2ZzjFOK9dS9fZcduefKlUkdbt08zGC62hPf6YF4FTRrvsICa2eVhLYpn4pKNWd8/PhGSMJCCSRGbp7KIl0qVa5F7XoCcNwgHP89zVWLfeGxhdhJYERWq83HCdvx+BSFUCetx35K0M/zCu9XfqYCqqMTPgZr+eKbBu5BH3Hf09C1UTfrt10YaRx+H01PHRjkr7ekRfzXHKYzd4hqjZLo89CsdtXWih3pEYs6Wc4AO1oQS85Itl8g8RyayqyAM4tg5RonTsOBxZKjElLWQtCeS2wyFEW9Upjvaye0cExWEUwFHmSBl0D989B1D5NQz7TXbXFtdJRcfiYUlZmhp8fO60OfHR1CYJvdrb8FTifS8WsiOw6SN+ygyn9dWWgu/2r3ZKgg27DdAm/7dMnmg6HhM3OZGNdtgTKXlgAPugumaJJIcEKOL/FB7ComwWbdaZTjlt+H9Sa8yUn+0Fp1wxmzkJIguSs/0Jh/EStubCy6esE3d4wZo7cBqVDKnTV0W7vRgEMWk1aIFGPEI2M0I095Fpe5MC325SYxC5UHEWnZSZ4qrxHzSWud+6CEFAkMYYNjuuIPoZJWZmVgVqDEV6adekZ0z0j6U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
