travis:
  secure:
    BINSTAR_TOKEN: KY84DCTfPjsCG1IonUgAufHEArCUHKdx6iN0gdluehN2zYOopo8P6dOWvaxF2lopGqwi6jpJrB6+VT+psXATbVYqt1hamKnSfU7H90v4zLx9+71LCiGti2GnXWXpfV1fRKqO7c8fsyZUhtpT4GdGthl0sgia5X0eA9KUG+fBph5bydSSfseUjPsIthkABYqc80w6U5fLAaAErZjCkdOmg+P1hxWQpTvpeAGbKr7MVnddwgcHx39wv3VK+eqGPvt543LYDNSRAB9r9HnBPCBxQilNuz4UTZYJQzdZiN3c7EGuyMXp16rO/6pIUCxhQAOapq4vbJlrJBQXk+oE/vMC+YaLc0+szdRRG7J3j8ZuQDSmZOGbh8X0Te5dVdjgoULkLGKqDpX7e1pdC5MEExD7hbIJdoGVYb+aAbFr7nI+/VH+97+fK7ZHExZXgezNEyRprQ/DQRVpYvlEusqlIoxXgTj1I2KM3rKXjgLN6sKCri9GWjkZW8NNms90YOpJQvvSc/dc05gDfBf7lwyzP3En4cs38n0zqTt0CubpVgN2aMHuSc44C02N3kIbZ4CdO9Vlrc5YQXLCk9YwsTgrFEI3t7PbfKjeIyOhcE4SYIwhCNbDkgIOGnPlCKdKA1YVyRKCDA1KgGwpQnk+LmsmVjr/BIdtz4mQIh9vHmEd/hdyKyI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
