appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: Er3NDESEffmSDIPe597JOgtMM1d55MDfG333+MDj2UExsMxjSCHM118ze5jTQxp2n+7raK/LusBSuFpjc6P/UoyqtWRl7u3kCzamrFKw9hkIiRR9fXGb/k6dcxalL9cTpzoqZG5jz0AnzqEMgxJgCMOyp0xYxNDGGQN0l95hIV2mdp6vGPNjH0W4TLlsYwSzI/bIy4uEFvP+NAYTF9r6pgz0/mg6DiOTcyhnfRCZWt6YFwzYVVJ3alktzcaGGO3VFj8MdU0iO61CCgSeAW3LWnTXJWyDcmZXEypAReg2FJm5tKQik4x1vfIGZnFopGCTG4nYgd87ZdK5+MXzEIlCpssHWicbRW0TEtiGIIALYSKfbIIpOpFyjwlu2ThMmenU4LaV1LY0qWV8f5n7Mqkk5yKa+0iYzBRWrGl/genBRgV6NU30f5Y09shihACqbXrMarViB6bH6dr/wqnsr8ZajYUKVZWD3Upyg3XJmLOm/tawh8OByGHI5mm169y5CNORvXMMPhfzSq0M5WuGRSW7WBOxLsFEWaKheLH0J7YVVPoHJF95qvHsAmlTDn4/4BoYXvBv48ll33FpA/HKqKU+HTEIo1Wxmtt4+SS3qnyHazDDAZlDrvuNjZYCxcodR+iaVAMR0RbRUkqK+pAgoaEbgBc6WLBXHId41jDnmsl66x8=}
